stages:
  - build-push-image

image: registry.gitlab.com/akamas/devops/build-base/build-base:1.3.1

build-and-push:
  stage: build-push-image
  tags:
    - docker
  script:
    - make build
    - make push