stages:
  - build-push-image

build-and-push:
  stage: build-push-image
  image: registry.gitlab.com/akamas/devops/build-base/build-base:1.7.0
  tags:
    - aws
  script:
    - make build && make push