variables:
  GIT_SUBMODULE_STRATEGY: normal
  GIT_DEPTH: 5

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS
      when: never
    - if: $CI_COMMIT_BRANCH

stages:
  - build-push-image
  - deploy
  - e2e
  - e2e-cleanup

build-and-push:
  stage: build-push-image
  tags:
    - Bash
  before_script:
     - docker login -u $GITLAB_COM_REGISTRY_USER -p $GITLAB_COM_REGISTRY_TOKEN registry.gitlab.com
  script:
    - make ci target=build
    - make ci target=push
  rules:
    - if: $CI_COMMIT_MESSAGE =~ /e2e[-_]skip|skip[-_]e2e/
      when: never
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - when: on_success

e2e-docker-compose:
  stage: e2e
  tags:
    - Bash
  before_script:
     - docker login -u $GITLAB_COM_REGISTRY_USER -p $GITLAB_COM_REGISTRY_TOKEN registry.gitlab.com
  script:
    - make e2e-docker
  needs:
    - build-and-push
  rules:
    - if: $CI_COMMIT_MESSAGE =~ /e2e[-_]skip|skip[-_]e2e/
      when: never
    - if: $CI_COMMIT_MESSAGE =~ /e2e/
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_BRANCH == 'master'
    - when: on_success

deploy-kube:
  tags:
    - Bash
  stage: deploy
  variables:
    KUBE_CLUSTER: dev
  script:
    - echo "Deploying akamas to cluster $KUBE_CLUSTER"
    - make provisioner target=debug
    - make build-values
    - make provisioner target=deploy-kube
  artifacts:
    exclude:
      - "*.jar"
    paths:
      - deploy/playbooks/target
    expire_in: 240 minutes
  needs:
    - build-and-push
  rules:
    - if: $CI_COMMIT_MESSAGE =~ /e2e[-_]skip|skip[-_]e2e/
      when: never
    - if: $CI_COMMIT_MESSAGE =~ /e2e/
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_BRANCH == 'master'
    - when: on_success

e2e-kube:
  tags:
    - Bash
  stage: e2e
  variables:
    KUBE_E2E: "true"
  script:
    - make ci target=e2e-kube
  needs:
    - deploy-kube
  artifacts:
    exclude:
      - "*.jar"
    when: always
    paths:
      - e2e/results
      - e2e/verifier/values
    expire_in: 2 days
  dependencies:
    - deploy-kube
  rules:
    - if: $CI_COMMIT_MESSAGE =~ /e2e[-_]skip|skip[-_]e2e/
      when: never
    - if: $CI_COMMIT_MESSAGE =~ /e2e/
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_BRANCH == 'master'
    - when: on_success

terminate-kube:
  tags:
    - Bash
  stage: e2e-cleanup
  variables:
    KUBE_CLUSTER: "dev"
  script:
    - echo "Terminating E2E environment"
    - make provisioner target=terminate-kube-environment
  allow_failure: true
  needs:
    - deploy-kube
    - e2e-kube
  rules:
    - if: $CI_COMMIT_MESSAGE =~ /e2e[-_]skip|skip[-_]e2e/
      when: never
    - when: always
