# docker build --build-arg="PASSWORD=<PASSWORD>" -f Dockerfile-cust .

ARG REGISTRY=485790562880.dkr.ecr.us-east-2.amazonaws.com/akamas
ARG TAG=1.2.2-dev
ARG PASSWORD

FROM ${REGISTRY}/management-container:${TAG}

RUN echo '${PASSWORD}' > /home/${BUILD_USER}/def_pwd && \
    echo "${BUILD_USER}:$(cat /home/${BUILD_USER}/def_pwd)" | sudo chpasswd
